// Code generated from internal models; DO NOT EDIT.
package model

import "time"

const (
	APIKeyEnvironmentProduction = "production"
	APIKeyEnvironmentTesting    = "testing"
)

type (
	APIKey struct {
		Created       time.Time `json:"created" yaml:"created"`
		ID            string    `json:"id" yaml:"id"`
		AutoGenerated bool      `json:"autoGenerated" yaml:"autoGenerated"`
		Description   string    `json:"description,omitempty" yaml:"description,omitempty"`
		Environment   string    `json:"environment,omitempty" yaml:"environment,omitempty"`
		Expiry        time.Time `json:"expiry,omitempty" yaml:"expiry,omitempty"`
		Key           string    `json:"key,omitempty" yaml:"key,omitempty"`
		UserID        string    `json:"userID,omitempty" yaml:"userID,omitempty"`
	}

	APIKeyFilter struct {
		MetadataFilter

		Environment          string    `json:"environment" query:"environment"`
		ExpiryAfter          time.Time `json:"expiryAfter" query:"expiryAfter"`
		ExpiryBefore         time.Time `json:"expiryBefore" query:"expiryBefore"`
		IncludeAutoGenerated bool      `json:"includeAutoGenerated"`

		UserID string `json:"userID" query:"userID"`
	}

	APIKeyUpdate struct {
		Description *string    `json:"description,omitempty"`
		Expiry      *time.Time `json:"expiry,omitempty"`
	}
)
